// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"

lv_obj_t * ui_About = NULL;
// event funtions

// build funtions

void ui_About_screen_init(void)
{
    ui_About = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

bool ui_About_is_ready(void)
{
    return (ui_About != NULL);
}


void ui_About_screen_destroy(void)
{
    if(ui_About) lv_obj_del(ui_About);

    // NULL screen variables
    ui_About = NULL;

}
