// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_ScanIcon;
extern lv_obj_t * ui_SendDataIcon;
extern lv_obj_t * ui_MemoryIcon;
extern lv_obj_t * ui_SettingIcon;
extern lv_obj_t * ui_InfoIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

