// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"
#include <math.h>

#define MENU_ITEM_COUNT 5
static lv_obj_t *menu_icons[MENU_ITEM_COUNT];
static int menu_selected = 0;

lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_ScanIcon = NULL;
lv_obj_t * ui_SendDataIcon = NULL;
lv_obj_t * ui_MemoryIcon = NULL;
lv_obj_t * ui_SettingIcon = NULL;
lv_obj_t * ui_InfoIcon = NULL;
// event funtions

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanIcon = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_ScanIcon, &ui_img_scan_png);
    lv_obj_set_width(ui_ScanIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_ScanIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_ScanIcon, 40);
    lv_obj_set_y(ui_ScanIcon, -61);
    lv_obj_set_align(ui_ScanIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ScanIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SendDataIcon = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_SendDataIcon, &ui_img_send_png);
    lv_obj_set_width(ui_SendDataIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_SendDataIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_SendDataIcon, 11);
    lv_obj_set_y(ui_SendDataIcon, 59);
    lv_obj_set_align(ui_SendDataIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendDataIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SendDataIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MemoryIcon = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_MemoryIcon, &ui_img_memory_png);
    lv_obj_set_width(ui_MemoryIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_MemoryIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_MemoryIcon, 81);
    lv_obj_set_y(ui_MemoryIcon, 10);
    lv_obj_set_align(ui_MemoryIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MemoryIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MemoryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingIcon = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_SettingIcon, &ui_img_setting_png);
    lv_obj_set_width(ui_SettingIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_SettingIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_SettingIcon, -77);
    lv_obj_set_y(ui_SettingIcon, 17);
    lv_obj_set_align(ui_SettingIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InfoIcon = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_InfoIcon, &ui_img_about_png);
    lv_obj_set_width(ui_InfoIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_InfoIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_InfoIcon, -40);
    lv_obj_set_y(ui_InfoIcon, -52);
    lv_obj_set_align(ui_InfoIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_InfoIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    menu_icons[0] = ui_ScanIcon;
    menu_icons[1] = ui_SendDataIcon;
    menu_icons[2] = ui_MemoryIcon;
    menu_icons[3] = ui_SettingIcon;
    menu_icons[4] = ui_InfoIcon;

    menu_update_positions();
}

void menu_update_positions(void)
{
    const int cx = 120;
    const int cy = 120;
    const int radius = 75;
    for(int i = 0; i < MENU_ITEM_COUNT; i++)
    {
        int pos = (i - menu_selected + MENU_ITEM_COUNT) % MENU_ITEM_COUNT;
        float angle_deg = -90 + pos * (360.0f / MENU_ITEM_COUNT);
        float angle_rad = angle_deg * 3.1415926f / 180.0f;
        int x = cx + radius * cosf(angle_rad);
        int y = cy + radius * sinf(angle_rad);
        lv_obj_set_pos(menu_icons[i], x - 24, y - 24);
        if(pos == 0)
        {
            lv_image_set_scale(menu_icons[i], 320);
            lv_obj_set_style_opa(menu_icons[i],
                                 LV_OPA_COVER,
                                 0);
        }
        else
        {
            lv_image_set_scale(menu_icons[i], 256);
            lv_obj_set_style_opa(menu_icons[i],
                                 LV_OPA_70,
                                 0);
        }
    }
}


void menu_next(void)          //turn right
{
    menu_selected++;

    if(menu_selected >= MENU_ITEM_COUNT)
        menu_selected = 0;

    menu_update_positions();
}

void menu_prev(void)         //turn left
{
    menu_selected--;

    if(menu_selected < 0)
        menu_selected = MENU_ITEM_COUNT - 1;

    menu_update_positions();
}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_ScanIcon = NULL;
    ui_SendDataIcon = NULL;
    ui_MemoryIcon = NULL;
    ui_SettingIcon = NULL;
    ui_InfoIcon = NULL;

}
