// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_MEMORY_H
#define UI_MEMORY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Memory
extern void ui_Memory_screen_init(void);
extern void ui_Memory_screen_destroy(void);
extern lv_obj_t * ui_Memory;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_PnlMemInfo;
extern lv_obj_t * ui_LblScanCountTxt;
extern lv_obj_t * ui_LblSendCountTxt;
extern lv_obj_t * ui_LblPercentTxt;
extern lv_obj_t * ui_LblScanCount;
extern lv_obj_t * ui_LblSendCount;
extern lv_obj_t * ui_LblPercent;
// CUSTOM VARIABLES

void ui_Memory_render(void);
void ui_memory_set_warning_visible(bool visible);



bool ui_Memory_is_ready(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

