// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_MEMORY_H
#define UI_MEMORY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Memory
extern void ui_Memory_screen_init(void);
extern void ui_Memory_screen_destroy(void);
extern lv_obj_t * ui_Memory;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

