// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"

lv_obj_t * uic_RedDot;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_RedDot = NULL;
lv_obj_t * ui_GreenDot = NULL;
lv_obj_t * ui_BlueDot = NULL;
lv_obj_t * ui_YellowDot = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ShowYellow_Animation(ui_YellowDot, 900);
        ShowBlue_Animation(ui_BlueDot, 600);
        ShowGreen_Animation(ui_GreenDot, 300);
        ShowRed_Animation(ui_RedDot, 0);
        extendUP_Animation(ui_RedDot, 2100);
        extendRight_Animation(ui_GreenDot, 1800);
        extendBot_Animation(ui_BlueDot, 1500);
        extendLeft_Animation(ui_YellowDot, 1200);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RedDot = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RedDot, 1);
    lv_obj_set_height(ui_RedDot, 0);
    lv_obj_set_align(ui_RedDot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RedDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RedDot, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedDot, lv_color_hex(0xFF0008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RedDot, lv_color_hex(0xE50C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RedDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_RedDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_RedDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GreenDot = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_GreenDot, 1);
    lv_obj_set_height(ui_GreenDot, 0);
    lv_obj_set_align(ui_GreenDot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GreenDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GreenDot, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GreenDot, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GreenDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GreenDot, lv_color_hex(0xE50C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GreenDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlueDot = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BlueDot, 1);
    lv_obj_set_height(ui_BlueDot, 0);
    lv_obj_set_align(ui_BlueDot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BlueDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlueDot, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlueDot, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlueDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BlueDot, lv_color_hex(0xE50C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BlueDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YellowDot = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_YellowDot, 1);
    lv_obj_set_height(ui_YellowDot, 0);
    lv_obj_set_align(ui_YellowDot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_YellowDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_YellowDot, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_YellowDot, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YellowDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_YellowDot, lv_color_hex(0xE50C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_YellowDot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
    uic_RedDot = ui_RedDot;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_RedDot = NULL;
    ui_RedDot = NULL;
    ui_GreenDot = NULL;
    ui_BlueDot = NULL;
    ui_YellowDot = NULL;

}
