// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"

lv_obj_t * ui_ScanPage = NULL;
lv_obj_t * ui_ArcN = NULL;
lv_obj_t * ui_ArcP = NULL;
lv_obj_t * ui_MeterBack = NULL;
lv_obj_t * ui_MeterNeedle = NULL;
lv_obj_t * ui_CurentValue = NULL;
lv_obj_t * ui_PulseCount = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Slider1 = NULL;
// event funtions

// build funtions

void ui_ScanPage_screen_init(void)
{
    ui_ScanPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScanPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcN = lv_arc_create(ui_ScanPage);
    lv_obj_set_width(ui_ArcN, 235);
    lv_obj_set_height(ui_ArcN, 235);
    lv_obj_set_align(ui_ArcN, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcN, 100);
    lv_arc_set_bg_angles(ui_ArcN, 180, 270);
    lv_arc_set_mode(ui_ArcN, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_ArcN, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcN, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcN, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcN, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcN, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_ArcN, &ui_img_ring_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcN, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcN, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcP = lv_arc_create(ui_ScanPage);
    lv_obj_set_width(ui_ArcP, 235);
    lv_obj_set_height(ui_ArcP, 235);
    lv_obj_set_align(ui_ArcP, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcP, 50);
    lv_arc_set_bg_angles(ui_ArcP, 270, 360);
    lv_obj_set_style_arc_color(ui_ArcP, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcP, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcP, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcP, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcP, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_ArcP, &ui_img_ring_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcP, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcP, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MeterBack = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_MeterBack, &ui_img_back_png);
    lv_obj_set_width(ui_MeterBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeterBack, 0);
    lv_obj_set_y(ui_MeterBack, -64);
    lv_obj_set_align(ui_MeterBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MeterBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeterNeedle = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_MeterNeedle, &ui_img_needle_png);
    lv_obj_set_width(ui_MeterNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeterNeedle, -1);
    lv_obj_set_y(ui_MeterNeedle, -40);
    lv_obj_set_align(ui_MeterNeedle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterNeedle, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MeterNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_MeterNeedle, 12, 79);
    lv_image_set_rotation(ui_MeterNeedle, 4);

    ui_CurentValue = lv_label_create(ui_ScanPage);
    lv_obj_set_width(ui_CurentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurentValue, 0);
    lv_obj_set_y(ui_CurentValue, 26);
    lv_obj_set_align(ui_CurentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurentValue, "1000");
    lv_obj_set_style_text_color(ui_CurentValue, lv_color_hex(0x35E12C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurentValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurentValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PulseCount = lv_label_create(ui_ScanPage);
    lv_obj_set_width(ui_PulseCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PulseCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PulseCount, 0);
    lv_obj_set_y(ui_PulseCount, 48);
    lv_obj_set_align(ui_PulseCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PulseCount, "1000");
    lv_obj_set_style_text_color(ui_PulseCount, lv_color_hex(0x35E12C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PulseCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PulseCount, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Image2, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image2, -72);
    lv_obj_set_y(ui_Image2, 40);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Image3, &ui_img_send_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image3, 67);
    lv_obj_set_y(ui_Image3, 45);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Image4, &ui_img_save_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image4, 15);
    lv_obj_set_y(ui_Image4, 85);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Image5, &ui_img_battery_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image5, -35);
    lv_obj_set_y(ui_Image5, 83);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image5, 300);
    lv_obj_set_style_bg_color(ui_Image5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_ScanPage);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 19);
    lv_obj_set_height(ui_Slider1, 27);
    lv_obj_set_x(ui_Slider1, -36);
    lv_obj_set_y(ui_Slider1, 80);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Slider1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x1CED11), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Slider1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_ScanPage_screen_destroy(void)
{
    if(ui_ScanPage) lv_obj_del(ui_ScanPage);

    // NULL screen variables
    ui_ScanPage = NULL;
    ui_ArcN = NULL;
    ui_ArcP = NULL;
    ui_MeterBack = NULL;
    ui_MeterNeedle = NULL;
    ui_CurentValue = NULL;
    ui_PulseCount = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Slider1 = NULL;

}
