// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_SENDDATA_H
#define UI_SENDDATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SendData
extern void ui_SendData_screen_init(void);
extern void ui_SendData_screen_destroy(void);
bool ui_SendData_is_ready(void);
void ui_SendData_update_bluetooth_status(void);
void ui_SendData_update_scan_count(uint32_t total_count);
void ui_SendData_update_scan_number(uint32_t current_number);

extern lv_obj_t * ui_SendData;
extern lv_obj_t * ui_BtIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

