// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"

lv_obj_t * ui_ScanMenu = NULL;
lv_obj_t * ui_manpc = NULL;
lv_obj_t * ui_autopc = NULL;
lv_obj_t * ui_automem = NULL;
lv_obj_t * ui_manmem = NULL;
// event funtions

// build funtions

void ui_ScanMenu_screen_init(void)
{
    ui_ScanMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScanMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_manpc = lv_image_create(ui_ScanMenu);
    lv_image_set_src(ui_manpc, &ui_img_manpc_png);
    lv_obj_set_width(ui_manpc, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_manpc, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_manpc, 3);
    lv_obj_set_y(ui_manpc, -72);
    lv_obj_set_align(ui_manpc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manpc, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_manpc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autopc = lv_image_create(ui_ScanMenu);
    lv_image_set_src(ui_autopc, &ui_img_autopc_png);
    lv_obj_set_width(ui_autopc, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_autopc, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_autopc, -68);
    lv_obj_set_y(ui_autopc, -9);
    lv_obj_set_align(ui_autopc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autopc, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_autopc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_automem = lv_image_create(ui_ScanMenu);
    lv_image_set_src(ui_automem, &ui_img_automem_png);
    lv_obj_set_width(ui_automem, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_automem, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_automem, -34);
    lv_obj_set_y(ui_automem, 63);
    lv_obj_set_align(ui_automem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_automem, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_automem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_manmem = lv_image_create(ui_ScanMenu);
    lv_image_set_src(ui_manmem, &ui_img_manmem_png);
    lv_obj_set_width(ui_manmem, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_manmem, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_manmem, 59);
    lv_obj_set_y(ui_manmem, 19);
    lv_obj_set_align(ui_manmem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manmem, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_manmem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScanMenu_screen_destroy(void)
{
    if(ui_ScanMenu) lv_obj_del(ui_ScanMenu);

    // NULL screen variables
    ui_ScanMenu = NULL;
    ui_manpc = NULL;
    ui_autopc = NULL;
    ui_automem = NULL;
    ui_manmem = NULL;

}
