// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RedDot;
extern lv_obj_t * ui_GreenDot;
extern lv_obj_t * ui_BlueDot;
extern lv_obj_t * ui_YellowDot;
extern lv_obj_t * ui_uiArcContainer;
extern lv_obj_t * ui_ArcRed;
extern lv_obj_t * ui_ArcYellow;
extern lv_obj_t * ui_ArcBlue;
extern lv_obj_t * ui_ArcGreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RedDot;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

