// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP
//ui_ScanPage.c

#include "../ui.h"
#include "brain.h" // حتما انکلود شود
#include "ui_ScanPage.h"
#include"scan_process.h"

lv_obj_t * ui_ScanPage = NULL;
lv_obj_t * ui_ArcN = NULL;
lv_obj_t * ui_ArcP = NULL;
lv_obj_t * ui_MeterBack = NULL;
lv_obj_t * ui_PulseCount = NULL;
lv_obj_t * ui_Blutooth = NULL;
lv_obj_t * ui_SendDataa = NULL;
lv_obj_t * ui_Save = NULL;
lv_obj_t * ui_Tap = NULL;
lv_obj_t * ui_Auto = NULL;
lv_obj_t * ui_BatL1 = NULL;
lv_obj_t * ui_BatL2 = NULL;
lv_obj_t * ui_BatL3 = NULL;
lv_obj_t * ui_BatL4 = NULL;
lv_obj_t * ui_BatL5 = NULL;
lv_obj_t * ui_needle = NULL;
lv_obj_t * ui_CurentValue = NULL;
lv_obj_t * ui_LblPulse = NULL;
lv_obj_t * ui_stop = NULL;
lv_obj_t * ui_play = NULL;


// Prearear function

static void scanpage_hide_mode_icons(void)
{
    if (ui_Auto)      lv_obj_add_flag(ui_Auto, LV_OBJ_FLAG_HIDDEN);
    if (ui_Save)      lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_HIDDEN);
    if (ui_Tap)       lv_obj_add_flag(ui_Tap, LV_OBJ_FLAG_HIDDEN);
    if (ui_SendDataa) lv_obj_add_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
}

static void ui_scanpage_set_battery_level(battery_level_t level)
{
    lv_obj_add_flag(ui_BatL1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BatL2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BatL3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BatL4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BatL5, LV_OBJ_FLAG_HIDDEN);

    switch (level) {
    case BATTERY_LEVEL_EMPTY:
        lv_obj_clear_flag(ui_BatL1, LV_OBJ_FLAG_HIDDEN);
        break;

    case BATTERY_LEVEL_25:
        lv_obj_clear_flag(ui_BatL2, LV_OBJ_FLAG_HIDDEN);
        break;

    case BATTERY_LEVEL_50:
        lv_obj_clear_flag(ui_BatL3, LV_OBJ_FLAG_HIDDEN);
        break;

    case BATTERY_LEVEL_75:
        lv_obj_clear_flag(ui_BatL4, LV_OBJ_FLAG_HIDDEN);
        break;

    case BATTERY_LEVEL_FULL:
    default:
        lv_obj_clear_flag(ui_BatL5, LV_OBJ_FLAG_HIDDEN);
        break;
    }
}


static void scanpage_apply_logic_mode(void)
{
    int mode = brain_get_scan_mode();

    scanpage_hide_mode_icons();

    switch (mode)
    {
        case 0: // manpc
            if (ui_Tap)       lv_obj_clear_flag(ui_Tap, LV_OBJ_FLAG_HIDDEN);
            if (ui_SendDataa) lv_obj_clear_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
            break;

        case 1: // autopc
            if (ui_Auto)      lv_obj_clear_flag(ui_Auto, LV_OBJ_FLAG_HIDDEN);
            if (ui_SendDataa) lv_obj_clear_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
            break;

        case 2: // automem
            if (ui_Auto)      lv_obj_clear_flag(ui_Auto, LV_OBJ_FLAG_HIDDEN);
            if (ui_Save)      lv_obj_clear_flag(ui_Save, LV_OBJ_FLAG_HIDDEN);
            break;

        case 3: // manmem
            if (ui_Tap)       lv_obj_clear_flag(ui_Tap, LV_OBJ_FLAG_HIDDEN);
            if (ui_Save)      lv_obj_clear_flag(ui_Save, LV_OBJ_FLAG_HIDDEN);
            break;

        default:
            break;
    }
}

void scanpage_apply_value(void)
{
    int current_value = scan_process_get_signed_value();
    int pulse_count = scan_process_get_pulse_count();
    int positive_arc = scan_process_get_positive_arc_value();
    int negative_arc = scan_process_get_negative_arc_value();
    int needle_angle = scan_process_get_needle_angle();

    lv_label_set_text_fmt(ui_CurentValue, "%d", current_value);
    lv_label_set_text_fmt(ui_PulseCount, "%d", pulse_count);

    lv_arc_set_value(ui_ArcP, positive_arc);
    lv_arc_set_value(ui_ArcN, negative_arc);

    lv_img_set_angle(ui_needle, needle_angle);
}



static void scanpage_apply_run_state(void)
{
    scan_sub_state_t sub_state = brain_get_scan_sub_state();

    if (ui_play) lv_obj_add_flag(ui_play, LV_OBJ_FLAG_HIDDEN);
    if (ui_stop) lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);

    if (sub_state == SCAN_STATE_RUNNING) {
        if (ui_play) lv_obj_clear_flag(ui_play, LV_OBJ_FLAG_HIDDEN);
    } else {
        if (ui_stop) lv_obj_clear_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);
    }
}




// event funtions

//

// static void scanpage_apply_run_state(void)
// {
//     // برای اطمینان: هر بار اول هر دو را مخفی کن
//    // lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);
//    // lv_obj_add_flag(ui_play, LV_OBJ_FLAG_HIDDEN);

//     // سپس بر اساس state فقط یکی را نشان بده
//     scan_sub_state_t st = brain_get_scan_sub_state();
//     if(st == SCAN_STATE_RUNNING) {
//         lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_HIDDEN);   // پلی
//     } else {
//         lv_obj_remove_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);   // استاپ
//     }
// }

// static void scanpage_apply_logic_mode(void)
// {
//     // دریافت حالت انتخاب شده از مغز
//     int mode = brain_get_scan_mode();


//     // ۲. بر اساس ایندکس منوی اسکن، المان‌های مربوطه را فعال می‌کنیم
//     switch(mode)
//     {
//         case 0: // ui_manpc (Manual + PC)
//             lv_obj_remove_flag(ui_Tap,       LV_OBJ_FLAG_HIDDEN);
//             lv_obj_remove_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
//             break;

//         case 1: // ui_autopc (Auto + PC)
//             lv_obj_remove_flag(ui_Auto,      LV_OBJ_FLAG_HIDDEN);
//             lv_obj_remove_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
//             break;

//         case 2: // ui_automem (Auto + Memory)
//             lv_obj_remove_flag(ui_Auto,      LV_OBJ_FLAG_HIDDEN);
//             lv_obj_remove_flag(ui_Save,      LV_OBJ_FLAG_HIDDEN);
//             break;

//         case 3: // ui_manmem (Manual + Memory)
//             lv_obj_remove_flag(ui_Tap,       LV_OBJ_FLAG_HIDDEN);
//             lv_obj_remove_flag(ui_Save,      LV_OBJ_FLAG_HIDDEN);
//             break;

//         default:
//             // حالت پیش‌فرض یا خطا (اختیاری)
//             break;
//     }
// }

//--------------------------------------
// Refresh page
//--------------------------------------
void ui_scanpage_render(void)
{
    if (!ui_ScanPage_is_ready()) {
        return;
    }

    scanpage_apply_logic_mode();
    scanpage_apply_run_state();
    scanpage_apply_value();
    ui_scanpage_set_battery_level(brain_get_battery_level());

    // اگر بعداً label / arc / needle / adc text هم داشتی،
    // همین‌جا فقط از getterها بخوان و update کن.
}





// build funtions

void ui_ScanPage_screen_init(void)
{
    if (ui_ScanPage != NULL) {
        return;
    }
    ui_ScanPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScanPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcN = lv_arc_create(ui_ScanPage);
    lv_obj_set_width(ui_ArcN, 235);
    lv_obj_set_height(ui_ArcN, 235);
    lv_obj_set_align(ui_ArcN, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcN, 100);
    lv_arc_set_bg_angles(ui_ArcN, 180, 270);
    lv_arc_set_mode(ui_ArcN, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_ArcN, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcN, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcN, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcN, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcN, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcN, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_ArcN, &ui_img_ring_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcN, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcN, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcP = lv_arc_create(ui_ScanPage);
    lv_obj_set_width(ui_ArcP, 235);
    lv_obj_set_height(ui_ArcP, 235);
    lv_obj_set_align(ui_ArcP, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcP, 50);
    lv_arc_set_bg_angles(ui_ArcP, 270, 360);
    lv_obj_set_style_arc_color(ui_ArcP, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcP, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcP, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcP, 18, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcP, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_ArcP, &ui_img_ring_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcP, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcP, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MeterBack = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_MeterBack, &ui_img_back_png);
    lv_obj_set_width(ui_MeterBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeterBack, 0);
    lv_obj_set_y(ui_MeterBack, -60);
    lv_obj_set_align(ui_MeterBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MeterBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PulseCount = lv_label_create(ui_ScanPage);
    lv_obj_set_width(ui_PulseCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PulseCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PulseCount, -30);
    lv_obj_set_y(ui_PulseCount, 81);
    lv_obj_set_align(ui_PulseCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PulseCount, "1000");
    lv_obj_set_style_text_color(ui_PulseCount, lv_color_hex(0x35E12C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PulseCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PulseCount, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blutooth = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Blutooth, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_Blutooth, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Blutooth, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Blutooth, -89);
    lv_obj_set_y(ui_Blutooth, 31);
    lv_obj_set_align(ui_Blutooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Blutooth, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Blutooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Blutooth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Blutooth, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendDataa = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_SendDataa, &ui_img_send_png);
    lv_obj_set_width(ui_SendDataa, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_SendDataa, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_SendDataa, 86);
    lv_obj_set_y(ui_SendDataa, 25);
    lv_obj_set_align(ui_SendDataa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SendDataa, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SendDataa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Save = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Save, &ui_img_save_png);
    lv_obj_set_width(ui_Save, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Save, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Save, 86);
    lv_obj_set_y(ui_Save, 28);
    lv_obj_set_align(ui_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Tap = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Tap, &ui_img_tap_48_png);
    lv_obj_set_width(ui_Tap, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Tap, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Tap, 29);
    lv_obj_set_y(ui_Tap, 29);
    lv_obj_set_align(ui_Tap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tap, LV_OBJ_FLAG_HIDDEN); 
    lv_obj_add_flag(ui_Tap, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Tap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Auto = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_Auto, &ui_img_auto_png);
    lv_obj_set_width(ui_Auto, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Auto, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Auto, 29);
    lv_obj_set_y(ui_Auto, 28);
    lv_obj_set_align(ui_Auto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Auto, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_Auto, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Auto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
     
    ui_BatL1 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_BatL1, &ui_img_level1_png);
    lv_obj_set_width(ui_BatL1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatL1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BatL1, -34);
    lv_obj_set_y(ui_BatL1, 19);
    lv_obj_set_align(ui_BatL1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatL1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_add_flag(ui_BatL1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_BatL1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatL2 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_BatL2, &ui_img_level2_png);
    lv_obj_set_width(ui_BatL2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatL2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BatL2, -34);
    lv_obj_set_y(ui_BatL2, 19);
    lv_obj_set_align(ui_BatL2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatL2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_add_flag(ui_BatL2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_BatL2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatL3 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_BatL3, &ui_img_level3_png);
    lv_obj_set_width(ui_BatL3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatL3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BatL3, -34);
    lv_obj_set_y(ui_BatL3, 19);
    lv_obj_set_align(ui_BatL3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatL3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_add_flag(ui_BatL3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_BatL3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatL4 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_BatL4, &ui_img_level4_png);
    lv_obj_set_width(ui_BatL4, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatL4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BatL4, -34);
    lv_obj_set_y(ui_BatL4, 19);
    lv_obj_set_align(ui_BatL4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatL4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_BatL4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatL4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatL5 = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_BatL5, &ui_img_full_png);
    lv_obj_set_width(ui_BatL5, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BatL5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BatL5, -34);
    lv_obj_set_y(ui_BatL5, 19);
    lv_obj_set_align(ui_BatL5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatL5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
   // lv_obj_add_flag(ui_BatL5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_BatL5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_needle = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_needle, &ui_img_needle_png);
    lv_obj_set_width(ui_needle, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_needle, LV_SIZE_CONTENT);    /// 81
    lv_obj_set_x(ui_needle, -1);
    lv_obj_set_y(ui_needle, -37);
    lv_obj_set_align(ui_needle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_needle, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_needle, 6, 75);
    lv_image_set_rotation(ui_needle, 9);
    lv_obj_set_style_bg_color(ui_needle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_needle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurentValue = lv_label_create(ui_ScanPage);
    lv_obj_set_width(ui_CurentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurentValue, 0);
    lv_obj_set_y(ui_CurentValue, -22);
    lv_obj_set_align(ui_CurentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurentValue, "1000");
    lv_obj_set_style_text_color(ui_CurentValue, lv_color_hex(0x35E12C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurentValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurentValue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPulse = lv_label_create(ui_ScanPage);
    lv_obj_set_width(ui_LblPulse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPulse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPulse, 33);
    lv_obj_set_y(ui_LblPulse, 72);
    lv_obj_set_align(ui_LblPulse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPulse, "پالس");
    lv_obj_set_style_base_dir(ui_LblPulse, LV_BASE_DIR_RTL, 0);
    lv_obj_set_style_text_font(ui_LblPulse, &ui_font_vazir20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stop = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_stop, &ui_img_stop_png);
    lv_obj_set_width(ui_stop, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_stop, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_stop, -53);
    lv_obj_set_y(ui_stop, 44);
    lv_obj_set_align(ui_stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play = lv_image_create(ui_ScanPage);
    lv_image_set_src(ui_play, &ui_img_play_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_play, -28);
    lv_obj_set_y(ui_play, 44);
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_HIDDEN);
    //lv_obj_add_flag(ui_play, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    if (ui_Auto)      lv_obj_add_flag(ui_Auto, LV_OBJ_FLAG_HIDDEN);
    if (ui_Save)      lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_HIDDEN);
    if (ui_Tap)       lv_obj_add_flag(ui_Tap, LV_OBJ_FLAG_HIDDEN);
    if (ui_SendDataa) lv_obj_add_flag(ui_SendDataa, LV_OBJ_FLAG_HIDDEN);
    if (ui_play)      lv_obj_add_flag(ui_play, LV_OBJ_FLAG_HIDDEN);
    if (ui_stop)      lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_HIDDEN);

    ui_scanpage_render();
    // scanpage_apply_logic_mode();
    // scanpage_apply_run_state();
}

bool ui_ScanPage_is_ready(void)
{
    return (ui_ScanPage != NULL) &&
           (ui_ArcN != NULL) &&
           (ui_ArcP != NULL) &&
           (ui_MeterBack != NULL) &&
           
           (ui_CurentValue != NULL) &&
           (ui_PulseCount != NULL) &&
           (ui_Blutooth != NULL) &&
           (ui_SendDataa != NULL) &&
           (ui_Save != NULL);
           
           
}


void ui_ScanPage_screen_destroy(void)
{
    if(ui_ScanPage) lv_obj_delete(ui_ScanPage);

    // NULL screen variables
    ui_ScanPage = NULL;
    ui_ArcN = NULL;
    ui_ArcP = NULL;
    ui_MeterBack = NULL;
    ui_PulseCount = NULL;
    ui_Blutooth = NULL;
    ui_SendDataa = NULL;
    ui_Save = NULL;
    ui_Tap = NULL;
    ui_Auto = NULL;
    ui_BatL1 = NULL;
    ui_BatL2 = NULL;
    ui_BatL3 = NULL;
    ui_BatL4 = NULL;
    ui_BatL5 = NULL;
    ui_needle = NULL;
    ui_CurentValue = NULL;
    ui_LblPulse = NULL;
    ui_Auto = NULL;
    ui_Save = NULL;
    ui_Tap = NULL;
    ui_SendDataa = NULL;
    ui_play = NULL;
    ui_stop = NULL;
}
