// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_SCANPAGE_H
#define UI_SCANPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScanPage
extern void ui_ScanPage_screen_init(void);
extern void ui_ScanPage_screen_destroy(void);
bool ui_ScanPage_is_ready(void);
extern lv_obj_t * ui_ScanPage;
extern lv_obj_t * ui_ArcN;
extern lv_obj_t * ui_ArcP;
extern lv_obj_t * ui_MeterBack;
extern lv_obj_t * ui_PulseCount;
extern lv_obj_t * ui_Blutooth;
extern lv_obj_t * ui_SendDataa;
extern lv_obj_t * ui_Save;
extern lv_obj_t * ui_Tap;
extern lv_obj_t * ui_Auto;
extern lv_obj_t * ui_BatL1;
extern lv_obj_t * ui_BatL2;
extern lv_obj_t * ui_BatL3;
extern lv_obj_t * ui_BatL4;
extern lv_obj_t * ui_BatL5;
extern lv_obj_t * ui_needle;
extern lv_obj_t * ui_CurentValue;
extern lv_obj_t * ui_LblPulse;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

