// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef UI_SCANMENU_H
#define UI_SCANMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScanMenu
extern void ui_ScanMenu_screen_init(void);
extern void ui_ScanMenu_screen_destroy(void); 
void scan_set_focused_index(int index);  
bool ui_ScanMenu_is_ready(void);    
extern lv_obj_t * ui_ScanMenu;
extern lv_obj_t * ui_manpc;
extern lv_obj_t * ui_autopc;
extern lv_obj_t * ui_automem;
extern lv_obj_t * ui_Image1;

// CUSTOM FUNCTION
int get_menu_selected(void);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif




void scan_set_focused_index(int index);
