// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#include "../ui.h"

lv_obj_t * ui_SendData = NULL;
// event funtions

// build funtions

void ui_SendData_screen_init(void)
{
    ui_SendData = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SendData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SendData_screen_destroy(void)
{
    if(ui_SendData) lv_obj_del(ui_SendData);

    // NULL screen variables
    ui_SendData = NULL;

}
