// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef _MAGI_ESP_UI_H
#define _MAGI_ESP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * extendRight_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowRed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowGreen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBlue_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowYellow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendLeft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendUP_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendBot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT

void startArcAnimations(int delay);
void startGoldenLabAnimation(int delay);
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
