// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: MAGI_ESP

#ifndef _MAGI_ESP_UI_H
#define _MAGI_ESP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SendData.h"
#include "screens/ui_Setting.h"
#include "screens/ui_ScanPage.h"
#include "screens/ui_Memory.h"
#include "screens/ui_About.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_MainMenu.h"
#include "screens/ui_ScanMenu.h"
///////////////////// VARIABLES ////////////////////

extern lv_anim_t * extendRight_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowRed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowGreen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBlue_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowYellow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendLeft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendUP_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * extendBot_Animation(lv_obj_t * TargetObject, int delay);
extern volatile bool splash_done;
extern lv_obj_t * ui_ScanMenu;
extern lv_obj_t * ui_manpc;
extern lv_obj_t * ui_autopc;
extern lv_obj_t * ui_automem;
extern lv_obj_t * ui_manmem;


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scan_png);    // assets/scan.png
LV_IMG_DECLARE(ui_img_send_png);    // assets/send.png
LV_IMG_DECLARE(ui_img_memory_png);    // assets/memory.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_about_png);    // assets/About.png
LV_IMG_DECLARE(ui_img_manpc_png);    // assets/manpc.png
LV_IMG_DECLARE(ui_img_autopc_png);    // assets/autopc.png
LV_IMG_DECLARE(ui_img_automem_png);    // assets/automem.png
LV_IMG_DECLARE(ui_img_manmem_png);    // assets/manmem.png
LV_IMG_DECLARE(ui_img_ring_png);    // assets/ring.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/Bluetooth.png
LV_IMG_DECLARE(ui_img_save_png);    // assets/Save.png
LV_IMG_DECLARE(ui_img_tap_48_png);    // assets/tap_48.png
LV_IMG_DECLARE(ui_img_auto_png);    // assets/auto.png
LV_IMG_DECLARE(ui_img_level1_png);    // assets/level1.png
LV_IMG_DECLARE(ui_img_level2_png);    // assets/level2.png
LV_IMG_DECLARE(ui_img_level3_png);    // assets/level3.png
LV_IMG_DECLARE(ui_img_level4_png);    // assets/level4.png
LV_IMG_DECLARE(ui_img_full_png);    // assets/full.png
LV_IMG_DECLARE(ui_img_needle_png);    // assets/needle.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_vazir40);
LV_FONT_DECLARE(vazir12);
LV_FONT_DECLARE(ui_font_vazir20);
// UI INIT

void startArcAnimations(int delay);
void startGoldenLabAnimation(int delay);
void ui_init(void);
void ui_destroy(void);
void splash_finished(void);
void ui_Screen1_cleanup_and_destroy(void);
void ui_ScanMenu_screen_init(void);
void ui_ScanMenu_screen_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif







